# BASE DE DATOS DESARROLLO
spring.datasource.url=jdbc:postgresql://10.144.239.221:5432/visus
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# SERVER DESARROLLO
server.port=8090
server.address=localhost

logging.file.name=logs/central-app.log
logging.file.path=logs

# LOGGING DESARROLLO
logging.level.com.visus=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# TIEMPO DE VIDA MÁXIMO DE UNA CONEXIÓN (en milisegundos)
# Debe ser MENOR que el timeout de inactividad de tu BD o red.
# 15 minutos suele ser seguro para la mayoría de entornos cloud.
spring.datasource.hikari.max-lifetime=1800000

# Tiempo que espera Hikari para obtener una conexión del pool
spring.datasource.hikari.connection-timeout=30000

# Tiempo máximo para validar una conexión antes de descartarla
spring.datasource.hikari.validation-timeout=5000

# Tiempo que una conexión puede estar inactiva antes de cerrarse (ms)
# 10 minutos
spring.datasource.hikari.idle-timeout=60000

spring.datasource.hikari.keepaliveTime=300000  

# Tamaño máximo del pool
spring.datasource.hikari.maximumPoolSize=10

# Flyway (migraciones automáticas)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=15

# Vistas excluidas del sistema de permisos
app.permissions.excluded-views=com.visus.central.ui.view.DepartamentoView,com.visus.central.ui.view.ProveedoresCrud