# BASE DE DATOS PRODUCCIÓN
spring.datasource.url=jdbc:postgresql://192.168.0.202:5432/visus
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# SERVER PRODUCCIÓN
server.port=8090
server.address=0.0.0.0

# LOGGING PRODUCCIÓN
logging.level.com.visus=WARN

# LOGGING EN ARCHIVO (opcional)
logging.file.name=/opt/log/visus/app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Vistas excluidas del sistema de permisos
app.permissions.excluded-views=com.visus.central.ui.view.DepartamentoView,com.visus.central.ui.view.ProveedoresCrud
