# CONFIGURACIÓN BASE COMÚN
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# NO definir perfil activo aquí - usar VM arguments al ejecutar

